version: '3.7'
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080
    container_name: backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    container_name: mongo
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    container_name: frontend